#
#   This file is part of uelp,
#   copyright (c) 2019 Sam Smith.
#
#   uelp is free software: you can redistribute it and/or modify it under the
#   terms of the GNU General Public License as published by the Free Software
#   Foundation, either version 3 of the License, or (at your option) any later
#   version.
#
#   uelp is distributed in the hope that it will be useful, but WITHOUT ANY
#   WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#   FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#   details.
#
#   You should have received a copy of the GNU General Public License along with
#   uelp. If not, see <http://www.gnu.org/licenses/>.
#

name: CI

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install updates
      run: sudo apt-get -y update
    - name: install dependencies
      run: sudo apt-get -y install sqlite3 libsqlite3-dev libzip-dev libxml2 libcmocka-dev libgtk-3-dev
    - name: make with gcc
      run: make
    - name: clean
      run: make clean
    - name: make with clang
      run: make CC=clang
    - name: clean
      run: make clean
    - name: make and run tests
      run: make test

  macos:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: brew install sqlite libzip libxml2 cmocka gtk+3 pkg-config
    - name: make with gcc
      run: make
    - name: clean
      run: make clean
    - name: make with clang
      run: make CC=clang
    - name: clean
      run: make clean
    - name: make and run tests
      run: make test
