name: CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install sqlite3 libsqlite3-dev libzip-dev libxml2
    - name: make with gcc
      run: make
    - name: clean
      run: make clean
    - name: make with clang
      run: make CC=clang
